
blockbeats:
    wss: https://api.theblockbeats.news/v1/open-api/home-xml

discord:
    webhook: https://discord.com/api/webhooks

cache:
    file: ~/.news_push_utils/file/blockbeats
    db: ~/.news_push_utils/db/blockbeats
